name: Nx CI lint, test, e2e
# from https://medium.com/emoteev-blog/10x-faster-ci-with-nx-and-github-actions-9a51fc4e82a6
# updated for npm
on: push
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      #  run all tests
      # - run: npx nx run-many --target=test --all
      # - run: npx nx run-many --target=lint --all

      # run tests for current changes
      - run: npx nx affected:lint
      - run: npx nx affected:test
      # run e2e tests for current changes
      - run: npx nx affected:e2e

      # Not yet, this is probably another job: cd
      # - run: nx run-many --target=build --all --prod
